import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"


const myFontRegurlar = localFont({
  src: './fonts/BeVietnamPro-Regular.ttf',
  weight: '400',
  variable: '--font-myFont-regular',
});


export const metadata: Metadata = {
  title: "Blog App",
  description: "Generated by HTShun",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${myFontRegurlar}  antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
